config/routes.rb
Rails.application.routes.draw do
  # get 'adminorders', to:'adminorders#index'
  # post 'adminorders', to: 'adminorders#update'
  resources :adminorders
  post 'adminorders/:id', to: 'adminorders#show'
  post '/adminorders/:id/edit', to: 'adminorders#edit'
  get '/adminorders/new', to: 'orders#new'

  get 'orders/new'
  post 'orders/create'
  get '/orders', to:'orders#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get 'users/new'
  get 'users/create'

  root "orders#index"
  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    # enum status: [:out_for_delivery, :delivered, :redeemed]
    validates :rfname, presence: true
    validates :rlname, presence: true
    validates :gcvalue, presence: true
    validates :phone, presence: true, length: { minimum: 10 ,maximum: 10 }
    validates :address, presence: true
    validates :uid, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true, uniqueness: true
    validates :email, presence: true
    validates :password, presence: true
end

app/controllers/adminorders_controller.rb
class AdminordersController < ApplicationController
  before_action :authorize
  
  def index
    @adminorders = Order.where(delivery_status: "Out for delivery")
  end

  def new
    @adminorders = Order.where(created_at: Date.today-30.days..Date.today+1)
    @orders_sum = Order.sum("apayable")
  end

  def show
    @adminorder = Order.find(params[:id])
  end

  def create
  end

  def edit
    @adminorder = Order.find(params[:aid])
    @adminorder.delivery_status = "Delivered"
    if @adminorder.save
      redirect_to '/adminorders'
    end
  end
  
  private
  def adminorders_params
    params.require(:adminorders).permit(:rfname, :rlname, :gcvalue, :phone, :address)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery wtih: :exception

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
        redirect_to '/login' unless current_user
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authorize

  def new
  end

  def create
    order = Order.new(orders_params)
    order.apayable = order.gcvalue * 0.05
    order.uid = current_user.id
    order.delivery_status = 'Out for delivery'
    if order.save
      redirect_to '/orders'
    else
      redirect_to '/orders/new'
    end
  end

  def index
    @orders = Order.where(:uid => current_user.id)
    p @orders
  end
  private
  def orders_params
    params.require(:order).permit(:rfname, :rlname, :gcvalue, :phone, :address)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password]) && user.email != 'admin@gmail.com'
      session[:user_id] = user.id
      redirect_to '/orders'
    elsif user.email == 'admin@gmail.com' && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/adminorders'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/orders'
    else
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/adminorders_helper.rb
module AdminordersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adminorders/_form.html.erb
<% time = Time.now.getutc %>
<p>Date: <%= time.to_s[0..10] %></p>
<table class="table">
<thead>
    <tr>
        <th scope="col">Order Id</th>
        <th scope="col">Recipient name</th>
        <th scope="col">Order Date</th>
        <th scope="col">Gift Card Value</th>
        <th scope="col">Commission</th>
        <th scope="col">Delivery Status</th>
        <th scope="col">Action</th>
    </tr>
</thead>
<tbody>
    <% @adminorders.each do |t|%>
    <tr>
        <th scope="row"><%= t.id %></th>
        <td><%= t.rfname %></td>
        <td><%= t.created_at.to_s[0..10] %></td>
        <td><%= t.gcvalue %></td>
        <td><%= t.apayable %></td>
        <td><%= t.delivery_status %></td>
        <td><%= button_to "Mark as delivered", edit_adminorder_url(t.id), params: { aid: t.id  }, :class=>"btn btn-primary" %></td> 
    </tr>
    <% end %>
</tbody>
</table>

app/views/adminorders/index.html.erb
<div class="container-fluid col-10">
    <h1>Admin Orders</h1>
    <%= render "form", adminorders: @adminorders %>
</div>

app/views/adminorders/new.html.erb
<div class="container-fluid col-10">
    <h1>Monthly Report</h1>
    <%= render "form", adminorders: @monthly_report %>
    <h5>Total Commission: <%= @orders_sum %></h5>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">GC App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav m-3">
        <% if current_user %>
        <li class="nav-item">
            <a class="nav-link" href="#">Signed in as <%= current_user.name %> </a>
        </li>
        <% if controller_name=='orders' %>
            <li class="nav-item">
            <a class="nav-link active" href="/orders/new">Create New Order</a>
            </li>
            <li class="nav-item">
            <a class="nav-link active" href="/orders">Orders History</a>
            </li>
        <% else %>
            <li class="nav-item">
            <a class="nav-link active" href="/adminorders/">Orders History</a>
            </li>
            <li class="nav-item">
            <a class="nav-link active" href="/adminorders/new">Monthly Report</a>
            </li>
        <% end %>
        <li class="nav-item">
            <%= link_to 'Logout', '/logout', :class=>"nav-link active" %>
        </li>
        <% else %>
        <li class="nav-item">
            <a class="nav-link <%= 'active' if controller_name=='sessions'%>" href="/login">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <%= 'active' if controller_name=='users'%>" href="/signup">Signup</a>
        </li>
        <% end %>
        </ul>
    </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftCard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "common/navbar"%>

    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container-fluid col-8">
    <h1>Orders</h1>
    <% time = Time.now.getutc %>
    <p>Date: <%= time.to_s[0..10] %></p>
    <table class="table">
    <thead>
        <tr>
            <th scope="col">Order Id</th>
            <th scope="col">Recipient name</th>
            <th scope="col">Order Date</th>
            <th scope="col">Gift Card Value</th>
            <th scope="col">Commission</th>
            <th scope="col">Delivery Status</th>
        </tr>
    </thead>
    <tbody>
        <% @orders.each do |t|%>
        <tr>
            <th scope="row"><%= t.id %></th>
            <td><%= t.rfname %></td>
            <td><%= t.created_at.to_s[0..10] %></td>
            <td><%= t.gcvalue %></td>
            <td><%= t.apayable %></td>
            <td><%= t.delivery_status %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>

app/views/orders/new.html.erb
<div class="container-fluid col-6 mt-lg-4">
    <h1>Create New Order</h1>
    <%= form_for :order, url: '/orders/create' do |f| %>
        <div class="col-auto">
            <%= f.label :recipient_first_name, :class=>"form-label" %>
            <%= f.text_field :rfname, :class=>"form-control" %>
        </div>
        <div class="col-auto">
            <%= f.label :recipient_last_name, :class=>"form-label" %>
            <%= f.text_field :rlname, :class=>"form-control" %>
        </div>
        <div class="col-auto">
            <%= f.label :gift_card_value, :class=>"form-label" %>
            <%= f.text_field :gcvalue, :class=>"form-control" %>
        </div>
        <div class="col-auto">
            <%= f.label :phone, :class=>"form-label" %>
            <%= f.number_field :phone, :class=>"form-control" %>
        </div>
        <div class="col-auto">
            <%= f.label :address, :class=>"form-label" %>
            <%= f.text_field :address, :class=>"form-control" %>
        </div>
        <div class="col-auto mt-lg-4">
            <%= f.submit "Create", :class=>"btn btn-primary mb-3" %>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="container-fluid col-6 mt-lg-4">
    <h1>Signup</h1>
    <%= form_for :user, url: '/users' do |f| %>
        <div class="col-auto">
            <%= f.label :name, :class=>"form-label" %>
            <%= f.text_field :name, :class=>"form-control" %>
        </div>
        <div class="col-auto">
            <%= f.label :email, :class=>"form-label" %>
            <%= f.text_field :email, :class=>"form-control" %>
        </div>
        <div class="col-auto">
            <%= f.label :password, :class=>"form-label" %> 
            <%= f.password_field :password, :class=>"form-control" %>
        </div>
        <div class="col-auto">
            <%= f.label :password_confirmation, :class=>"form-label" %>
            <%= f.password_field :password_confirmation, :class=>"form-control" %>
        </div>
        <div class="col-auto mt-lg-4">
        <%= f.submit "Sign up", :class=>"btn btn-primary mb-3" %>
        </div>

    <% end %>
</div>